### ISSUE TITLE
Mobius should have a self-contained demo of a rotate-able cube

### ISSUE THREAD

**Issue by samreid** [phetsims/mobius#5]
From https://github.com/phetsims/density-buoyancy-common/issues/5, it seems like mobius should have a basic "hello world" that shows a rotate-able cube or something like that.

**Comment by jonathanolson** [comment]
Made mobius runnable. Added a rotating cube, and tossed some Scenery content in the 3D scene on the front of it. Does this work for the purpose?

**Comment by samreid** [comment]
This looks really great, thanks!  Closing.
